[package]
name = "steviegoodman/component-extensions"
description = "A collection of utility extensions for sleitnick's Component package."
version = "1.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "src",
    "src/*.lua",
    "wally.toml",
    "default.project.json",
]

[dependencies]
Waiter = "steviegoodman/waiter@7.0.0"